//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using WebApplication1.Models.Code;

    public partial class Employee 
    {
        public string DepNo { set; get; }

        public string EmpNo { get; set; }

        public string EmpFirstName { get; set; }

        public string EmpLastName { get; set; }

        public string Tel { set; get; }

        public string Addr { set; get; }

        /// <summary>員工類型 </summary>
        public string EmpType { set; get; }
    }
}
