//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 之類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Menu", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Member 的當地語系化字串。
        /// </summary>
        internal static string Menu_1000 {
            get {
                return ResourceManager.GetString("Menu_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personal 的當地語系化字串。
        /// </summary>
        internal static string Menu_1001 {
            get {
                return ResourceManager.GetString("Menu_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change PassWord 的當地語系化字串。
        /// </summary>
        internal static string Menu_1002 {
            get {
                return ResourceManager.GetString("Menu_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MemberMangement 的當地語系化字串。
        /// </summary>
        internal static string Menu_1003 {
            get {
                return ResourceManager.GetString("Menu_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AdviserMangement 的當地語系化字串。
        /// </summary>
        internal static string Menu_2000 {
            get {
                return ResourceManager.GetString("Menu_2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AdviserMangement 的當地語系化字串。
        /// </summary>
        internal static string Menu_2001 {
            get {
                return ResourceManager.GetString("Menu_2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Investment  的當地語系化字串。
        /// </summary>
        internal static string Menu_3000 {
            get {
                return ResourceManager.GetString("Menu_3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Trade 的當地語系化字串。
        /// </summary>
        internal static string Menu_3001 {
            get {
                return ResourceManager.GetString("Menu_3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MemberDeposit 的當地語系化字串。
        /// </summary>
        internal static string Menu_3002 {
            get {
                return ResourceManager.GetString("Menu_3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MemberWithdrawal 的當地語系化字串。
        /// </summary>
        internal static string Menu_3003 {
            get {
                return ResourceManager.GetString("Menu_3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bonus 的當地語系化字串。
        /// </summary>
        internal static string Menu_3004 {
            get {
                return ResourceManager.GetString("Menu_3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Report 的當地語系化字串。
        /// </summary>
        internal static string Menu_4000 {
            get {
                return ResourceManager.GetString("Menu_4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TransactionHistory 的當地語系化字串。
        /// </summary>
        internal static string Menu_4001 {
            get {
                return ResourceManager.GetString("Menu_4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TradeRecorde 的當地語系化字串。
        /// </summary>
        internal static string Menu_4002 {
            get {
                return ResourceManager.GetString("Menu_4002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set Up 的當地語系化字串。
        /// </summary>
        internal static string Menu_5000 {
            get {
                return ResourceManager.GetString("Menu_5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login Out 的當地語系化字串。
        /// </summary>
        internal static string Menu_6000 {
            get {
                return ResourceManager.GetString("Menu_6000", resourceCulture);
            }
        }
    }
}
