//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 之類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCustomer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCustomer() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceCustomer", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string AuditTpyes_Cancel {
            get {
                return ResourceManager.GetString("AuditTpyes_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NO 的當地語系化字串。
        /// </summary>
        internal static string AuditTpyes_NO {
            get {
                return ResourceManager.GetString("AuditTpyes_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NotYet 的當地語系化字串。
        /// </summary>
        internal static string AuditTpyes_NotYet {
            get {
                return ResourceManager.GetString("AuditTpyes_NotYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        internal static string AuditTpyes_OK {
            get {
                return ResourceManager.GetString("AuditTpyes_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back 的當地語系化字串。
        /// </summary>
        internal static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Modify 的當地語系化字串。
        /// </summary>
        internal static string Btn_Modify {
            get {
                return ResourceManager.GetString("Btn_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        internal static string Label_Account {
            get {
                return ResourceManager.GetString("Label_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Audit 的當地語系化字串。
        /// </summary>
        internal static string Label_Audit {
            get {
                return ResourceManager.GetString("Label_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BirthDay 的當地語系化字串。
        /// </summary>
        internal static string Label_BirthDay {
            get {
                return ResourceManager.GetString("Label_BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EditTime 的當地語系化字串。
        /// </summary>
        internal static string Label_EditTime {
            get {
                return ResourceManager.GetString("Label_EditTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Email 的當地語系化字串。
        /// </summary>
        internal static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FirstName 的當地語系化字串。
        /// </summary>
        internal static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gender 的當地語系化字串。
        /// </summary>
        internal static string Label_Gender {
            get {
                return ResourceManager.GetString("Label_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HomeAddr 的當地語系化字串。
        /// </summary>
        internal static string Label_HomeAddr {
            get {
                return ResourceManager.GetString("Label_HomeAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        internal static string Label_ID {
            get {
                return ResourceManager.GetString("Label_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IsEnable 的當地語系化字串。
        /// </summary>
        internal static string Label_IsEnable {
            get {
                return ResourceManager.GetString("Label_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LastName 的當地語系化字串。
        /// </summary>
        internal static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NickName 的當地語系化字串。
        /// </summary>
        internal static string Label_NickName {
            get {
                return ResourceManager.GetString("Label_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phone 的當地語系化字串。
        /// </summary>
        internal static string Label_Phone {
            get {
                return ResourceManager.GetString("Label_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remark 的當地語系化字串。
        /// </summary>
        internal static string Label_Remark {
            get {
                return ResourceManager.GetString("Label_Remark", resourceCulture);
            }
        }
    }
}
