//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 之類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceTransaction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTransaction() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceTransaction", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Bank Account 的當地語系化字串。
        /// </summary>
        internal static string Label_BankAccount {
            get {
                return ResourceManager.GetString("Label_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BankName 的當地語系化字串。
        /// </summary>
        internal static string Label_BankName {
            get {
                return ResourceManager.GetString("Label_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bank Branch  Name 的當地語系化字串。
        /// </summary>
        internal static string Label_BranchName {
            get {
                return ResourceManager.GetString("Label_BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Draw 的當地語系化字串。
        /// </summary>
        internal static string Label_Draw {
            get {
                return ResourceManager.GetString("Label_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TransactionType 的當地語系化字串。
        /// </summary>
        internal static string Label_TransactionType {
            get {
                return ResourceManager.GetString("Label_TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Deposit 的當地語系化字串。
        /// </summary>
        internal static string TransType_Deposit {
            get {
                return ResourceManager.GetString("TransType_Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Withdraw 的當地語系化字串。
        /// </summary>
        internal static string TransType_Withdraw {
            get {
                return ResourceManager.GetString("TransType_Withdraw", resourceCulture);
            }
        }
    }
}
