//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 之類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 AddNewData 的當地語系化字串。
        /// </summary>
        internal static string AddData {
            get {
                return ResourceManager.GetString("AddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 等待五秒或點擊馬上跳轉 的當地語系化字串。
        /// </summary>
        internal static string AlertMessage_Auto_Direct_Page {
            get {
                return ResourceManager.GetString("AlertMessage_Auto_Direct_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string AuditTpyes_Cancel {
            get {
                return ResourceManager.GetString("AuditTpyes_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string AuditTpyes_Cancel1 {
            get {
                return ResourceManager.GetString("AuditTpyes_Cancel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NO 的當地語系化字串。
        /// </summary>
        internal static string AuditTpyes_NO {
            get {
                return ResourceManager.GetString("AuditTpyes_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NO 的當地語系化字串。
        /// </summary>
        internal static string AuditTpyes_NO1 {
            get {
                return ResourceManager.GetString("AuditTpyes_NO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NotYet 的當地語系化字串。
        /// </summary>
        internal static string AuditTpyes_NotYet {
            get {
                return ResourceManager.GetString("AuditTpyes_NotYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NotYet 的當地語系化字串。
        /// </summary>
        internal static string AuditTpyes_NotYet1 {
            get {
                return ResourceManager.GetString("AuditTpyes_NotYet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        internal static string AuditTpyes_OK {
            get {
                return ResourceManager.GetString("AuditTpyes_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        internal static string AuditTpyes_OK1 {
            get {
                return ResourceManager.GetString("AuditTpyes_OK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change 的當地語系化字串。
        /// </summary>
        internal static string Btn_Change {
            get {
                return ResourceManager.GetString("Btn_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        internal static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send 的當地語系化字串。
        /// </summary>
        internal static string Btn_Send {
            get {
                return ResourceManager.GetString("Btn_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter email of register account.  的當地語系化字串。
        /// </summary>
        internal static string ForGetPassWord_Email {
            get {
                return ResourceManager.GetString("ForGetPassWord_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fmale 的當地語系化字串。
        /// </summary>
        internal static string Gender_Fmale {
            get {
                return ResourceManager.GetString("Gender_Fmale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Male 的當地語系化字串。
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LoginError 的當地語系化字串。
        /// </summary>
        internal static string Global_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wait 5 seconds or click to go next right away. 的當地語系化字串。
        /// </summary>
        internal static string jump {
            get {
                return ResourceManager.GetString("jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Forget Pass Word 的當地語系化字串。
        /// </summary>
        internal static string Label_ForgetPassWord {
            get {
                return ResourceManager.GetString("Label_ForgetPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable 的當地語系化字串。
        /// </summary>
        internal static string Label_IsEnable {
            get {
                return ResourceManager.GetString("Label_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        internal static string Login_Account {
            get {
                return ResourceManager.GetString("Login_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please make sure your account or password is correct. 的當地語系化字串。
        /// </summary>
        internal static string Login_AccountError {
            get {
                return ResourceManager.GetString("Login_AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PassWord 的當地語系化字串。
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Submit 的當地語系化字串。
        /// </summary>
        internal static string Login_Submit {
            get {
                return ResourceManager.GetString("Login_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login 的當地語系化字串。
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        internal static string Register_Account {
            get {
                return ResourceManager.GetString("Register_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 以電子郵件信箱註冊帳號 的當地語系化字串。
        /// </summary>
        internal static string Register_AccountRemark {
            get {
                return ResourceManager.GetString("Register_AccountRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back 的當地語系化字串。
        /// </summary>
        internal static string Register_Back {
            get {
                return ResourceManager.GetString("Register_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BirthDay 的當地語系化字串。
        /// </summary>
        internal static string Register_BirthDay {
            get {
                return ResourceManager.GetString("Register_BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RegisterError 的當地語系化字串。
        /// </summary>
        internal static string Register_Error {
            get {
                return ResourceManager.GetString("Register_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The Account has been registered. 的當地語系化字串。
        /// </summary>
        internal static string Register_Error_ExsitAccount {
            get {
                return ResourceManager.GetString("Register_Error_ExsitAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FirstName 的當地語系化字串。
        /// </summary>
        internal static string Register_FirstName {
            get {
                return ResourceManager.GetString("Register_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gender 的當地語系化字串。
        /// </summary>
        internal static string Register_Gender {
            get {
                return ResourceManager.GetString("Register_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HomeAddress 的當地語系化字串。
        /// </summary>
        internal static string Register_HomeAddr {
            get {
                return ResourceManager.GetString("Register_HomeAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        internal static string Register_ID {
            get {
                return ResourceManager.GetString("Register_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LastName 的當地語系化字串。
        /// </summary>
        internal static string Register_LastName {
            get {
                return ResourceManager.GetString("Register_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Member 的當地語系化字串。
        /// </summary>
        internal static string Register_Member {
            get {
                return ResourceManager.GetString("Register_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NickName 的當地語系化字串。
        /// </summary>
        internal static string Register_NickName {
            get {
                return ResourceManager.GetString("Register_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 註冊完成後會發送信件到註冊的信箱，待審核通過後才可以使用系統。 的當地語系化字串。
        /// </summary>
        internal static string Register_Note {
            get {
                return ResourceManager.GetString("Register_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phone 的當地語系化字串。
        /// </summary>
        internal static string Register_Phone {
            get {
                return ResourceManager.GetString("Register_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Register 的當地語系化字串。
        /// </summary>
        internal static string Register_Register {
            get {
                return ResourceManager.GetString("Register_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reigster Success  的當地語系化字串。
        /// </summary>
        internal static string Register_Success {
            get {
                return ResourceManager.GetString("Register_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reigster Member 的當地語系化字串。
        /// </summary>
        internal static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bonus 的當地語系化字串。
        /// </summary>
        internal static string TransTypes_Bonus {
            get {
                return ResourceManager.GetString("TransTypes_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Deposit 的當地語系化字串。
        /// </summary>
        internal static string TransTypes_Deposit {
            get {
                return ResourceManager.GetString("TransTypes_Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dividend 的當地語系化字串。
        /// </summary>
        internal static string TransTypes_Dividend {
            get {
                return ResourceManager.GetString("TransTypes_Dividend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loss 的當地語系化字串。
        /// </summary>
        internal static string TransTypes_Loss {
            get {
                return ResourceManager.GetString("TransTypes_Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settle 的當地語系化字串。
        /// </summary>
        internal static string TransTypes_Settle {
            get {
                return ResourceManager.GetString("TransTypes_Settle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Withdrawal 的當地語系化字串。
        /// </summary>
        internal static string TransTypes_Withdrawal {
            get {
                return ResourceManager.GetString("TransTypes_Withdrawal", resourceCulture);
            }
        }
    }
}
