//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu_Engineering {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class AppConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppConfig defaultInstance = ((AppConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppConfig())));
        
        public static AppConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=127.0.0.1;Initial Catalog=MenuEngineering;User Id=sa;Password=dcms;Ap" +
            "plication Name=DcmsHr")]
        public string BaseConncection {
            get {
                return ((string)(this["BaseConncection"]));
            }
            set {
                this["BaseConncection"] = value;
            }
        }
    }
}
